esphome:
  name: "lora"
  friendly_name: "LoRa"

esp32:
  board: esp32-c6-devkitm-1
  framework:
    type: esp-idf

logger:
  hardware_uart: UART0
  level: DEBUG

spi:
  clk_pin: GPIO23
  mosi_pin: GPIO22
  miso_pin: GPIO21

substitutions:
  cs_pin: GPIO5
  reset_pin: GPIO2
  dio0_pin: GPIO7

# <<: !include common/condition.yaml
# <<: !include common/queue.yaml
# <<: !include common/mode.yaml
# <<: !include common/switch.yaml
# <<: !include common/send.yaml
# <<: !include common/recv.yaml
# <<: !include common/echo.yaml
# <<: !include common/deepsleep.yaml
# <<: !include common/deepsleep_recv.yaml
