esphome:
  name: "lora"
  friendly_name: "LoRa"

esp32:
  board: ttgo-lora32-v21
  framework:
    type: esp-idf

logger:
  level: DEBUG

spi:
  clk_pin: GPIO5
  mosi_pin: GPIO27
  miso_pin: GPIO19

substitutions:
  cs_pin: GPIO18
  reset_pin: GPI23
  dio0_pin: GPIO26

# <<: !include common/condition.yaml
# <<: !include common/queue.yaml
# <<: !include common/mode.yaml
# <<: !include common/switch.yaml
# <<: !include common/send.yaml
# <<: !include common/recv.yaml
# <<: !include common/echo.yaml
# <<: !include common/deepsleep.yaml
# <<: !include common/deepsleep_recv.yaml
